var keyMirror = require('keymirror');

let Constants = keyMirror({
	ADD_EXPENSE_POST_SUCCESS: null,
	ADD_EXPENSE_POST_ERROR: null,
	DELETE_EXPENSE_POST_SUCCESS: null,
	DELETE_EXPENSE_POST_ERROR: null,
	FETCH_EXPENSE_POSTS_SUCCESS: null,
	FETCH_EXPENSE_POSTS_ERROR: null,
	FETCH_DEPTS_SUCCESS: null,
	FETCH_DEPTS_ERROR: null,
	ADD_EXPENSES_LIST_ERROR: null,
	ADD_EXPENSES_LIST_SUCCESS: null,
	DELETE_EXPENSES_LIST_SUCCESS: null,
	DELETE_EXPENSES_LIST_ERROR: null,
	LOCK_EXPENSES_LIST_SUCCESS: null,
	LOCK_EXPENSES_LIST_ERROR: null,
	FETCH_EXPENSES_LISTS_SUCCESS: null,
	FETCH_EXPENSES_LISTS_ERROR: null,
	SET_DISPENSES_SUCCESS: null,
	SET_DISPENSES_ERROR: null,
	ACTIVE_LIST_SUCCESS: null,
	ACTIVE_LIST_ERROR: null
});

module.exports = Constants;